### ISSUE TITLE
New should accept a limit of 0

### ISSUE THREAD

**Issue by kylrth** [marusama/semaphore#5]
It may not appear to be useful at first glance, but I think it would be reasonable for `New` and `SetLimit` to accept a limit of 0 in cases where the semaphore coordinates access to a number of resources that is changing. It's reasonable for the number of resources to drop to zero and then increase again, all while goroutines await an increase in resources. Thoughts?

**Comment by marusama** [comment]
LGTM, contributions/pull requests welcome) @kylrth can you?

**Comment by kylrth** [comment]
#6

**Comment by marusama** [comment]
Fixed in [v2.5.0](https://github.com/marusama/semaphore/releases/tag/v2.5.0)
